using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace Stratego {
    public partial class MainWindow : Window {
        private void PopulateButtonDict() {
            Component.Display.Buttons bc = (Component.Display.Buttons)Entity.DisplayEntity.Instance.components["Buttons"];
            Dictionary<int, Button> buttons = bc.buttons;
            buttons.Add(0, pauseBtn);
            buttons.Add(1, btn_01);
            buttons.Add(2, btn_02);
            buttons.Add(3, btn_03);
            buttons.Add(4, btn_04);
            buttons.Add(5, btn_05);
            buttons.Add(6, btn_06);
            buttons.Add(7, btn_07);
            buttons.Add(8, btn_08);
            buttons.Add(9, btn_09);
            buttons.Add(10, btn_10);
            buttons.Add(11, btn_11);
            buttons.Add(12, btn_12);
            buttons.Add(13, btn_13);
            buttons.Add(14, btn_14);
            buttons.Add(15, btn_15);
            buttons.Add(16, btn_16);
            buttons.Add(17, btn_17);
            buttons.Add(18, btn_18);
            buttons.Add(19, btn_19);
            buttons.Add(20, btn_20);
            buttons.Add(21, btn_21);
            buttons.Add(22, btn_22);
            buttons.Add(23, btn_23);
            buttons.Add(24, btn_24);
            buttons.Add(25, btn_25);
            buttons.Add(26, btn_26);
            buttons.Add(27, btn_27);
            buttons.Add(28, btn_28);
            buttons.Add(29, btn_29);
            buttons.Add(30, btn_30);
            buttons.Add(31, btn_31);
            buttons.Add(32, btn_32);
            buttons.Add(33, btn_33);
            buttons.Add(34, btn_34);
            buttons.Add(35, btn_35);
            buttons.Add(36, btn_36);
            buttons.Add(37, btn_37);
            buttons.Add(38, btn_38);
            buttons.Add(39, btn_39);
            buttons.Add(40, btn_40);
            buttons.Add(41, btn_41);
            buttons.Add(42, btn_42);
            buttons.Add(43, btn_43);
            buttons.Add(44, btn_44);
            buttons.Add(45, btn_45);
            buttons.Add(46, btn_46);
            buttons.Add(47, btn_47);
            buttons.Add(48, btn_48);
            buttons.Add(49, btn_49);
            buttons.Add(50, btn_50);
            buttons.Add(51, btn_51);
            buttons.Add(52, btn_52);
            buttons.Add(53, btn_53);
            buttons.Add(54, btn_54);
            buttons.Add(55, btn_55);
            buttons.Add(56, btn_56);
            buttons.Add(57, btn_57);
            buttons.Add(58, btn_58);
            buttons.Add(59, btn_59);
            buttons.Add(60, btn_60);
            buttons.Add(61, btn_61);
            buttons.Add(62, btn_62);
            buttons.Add(63, btn_63);
            buttons.Add(64, btn_64);
            buttons.Add(65, btn_65);
            buttons.Add(66, btn_66);
            buttons.Add(67, btn_67);
            buttons.Add(68, btn_68);
            buttons.Add(69, btn_69);
            buttons.Add(70, btn_70);
            buttons.Add(71, btn_71);
            buttons.Add(72, btn_72);
            buttons.Add(73, btn_73);
            buttons.Add(74, btn_74);
            buttons.Add(75, btn_75);
            buttons.Add(76, btn_76);
            buttons.Add(77, btn_77);
            buttons.Add(78, btn_78);
            buttons.Add(79, btn_79);
            buttons.Add(80, btn_80);
            buttons.Add(81, btn_81);
            buttons.Add(82, btn_82);
            buttons.Add(83, btn_83);
            buttons.Add(84, btn_84);
            buttons.Add(85, btn_85);
            buttons.Add(86, btn_86);
            buttons.Add(87, btn_87);
            buttons.Add(88, btn_88);
            buttons.Add(89, btn_89);
            buttons.Add(90, btn_90);
            buttons.Add(91, btn_91);
            buttons.Add(92, btn_92);
            buttons.Add(93, btn_93);
            buttons.Add(94, btn_94);
            buttons.Add(95, btn_95);
            buttons.Add(96, btn_96);
            buttons.Add(97, btn_97);
            buttons.Add(98, btn_98);
            buttons.Add(99, btn_99);
            buttons.Add(100, btn_100);
        }
        private void PopulateGroupBoxDict() {
            Component.Display.GroupBoxes gbc = (Component.Display.GroupBoxes)Entity.DisplayEntity.Instance.components["GroupBoxes"];
            Dictionary<string, GroupBox> groupBoxes = gbc.groupBoxes;
            groupBoxes.Add("Graveyard", graveyardGroupBox);
            groupBoxes.Add("History", historyGroupBox);
            groupBoxes.Add("Board", boardGroupBox);
        }
        private void PopulateListboxesDict() {
            Component.Display.ListBoxes lbc = (Component.Display.ListBoxes)Entity.DisplayEntity.Instance.components["ListBoxes"];
            Dictionary<string, ListBox> listBoxes = lbc.listBoxes;
            listBoxes.Add("History", historyListBox);
            listBoxes.Add("Graveyard1", graveyard1ListBox);
            listBoxes.Add("Graveyard2", graveyard2ListBox);
        }
    }
}